DEFAULT_ANDROID_NDK_ROOT=~/Android/Sdk/ndk-bundle/
ANDROID_NDK_ROOT="${ANDROID_NDK_ROOT:-${DEFAULT_ANDROID_NDK_ROOT}}"

export ANDROID_NDK_ROOT=`realpath $ANDROID_NDK_ROOT`

BUILD_PATH=../wownerujo-build

DEFAULT_EXTERNAL_LIBS_BUILD_ROOT=`pwd`/${BUILD_PATH}/external-libs/
EXTERNAL_LIBS_BUILD_ROOT="${EXTERNAL_LIBS_BUILD_ROOT:-${DEFAULT_EXTERNAL_LIBS_BUILD_ROOT}}"

export EXTERNAL_LIBS_BUILD_ROOT=${EXTERNAL_LIBS_BUILD_ROOT%/}

DEFAULT_NPROC=$(nproc)
NPROC="${NPROC:-${DEFAULT_NPROC}}"

export NPROC


